codecod:
  notify:
    after_n_builds: 1
  strict_yaml_branch: main

coverage:
  range: '50...100'
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: off

file_management:
  default_rules:
    statususes:
      - type: project
        target: auto
        threshold: 2%

comment:
  require_changes: true
  after_n_builds: 1
