nodeLinker: node-modules

enableGlobalCache: true

gitHooksPath: .github/hooks
plugins: 
  - path: .yarn/plugins/@yarnpkg/plugin-git-hooks.cjs
    spec: "https://raw.githubusercontent.com/truffle/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugin-git-hooks.js"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
